---
title: ""
author: ""
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(stringr)
library(tidyr)
library(purrr)
```



```{r}
diabetes_full <- read.csv("/Users/benabijah/Downloads/diabetes_full.csv", header = T) %>%
  mutate(BENE_ID = as.character(BENE_ID),
         CCSR_CATEGORY_DESCRIPTION = gsub("[/ \\-]", ".", CCSR_CATEGORY_DESCRIPTION))

# define the list of other diagnoses
diab_names <- c("Prediabetes","Diabetes.mellitus.without.complication","Diabetes.mellitus.with.complication")

other_diagnoses <- unique(diabetes_full$CCSR_CATEGORY_DESCRIPTION[
  !(diabetes_full$CCSR_CATEGORY_DESCRIPTION %in% diab_names)])
```


```{r}
# get data for all non-diabetes diagnoses
other_diagnoses_data <- diabetes_full %>%
  filter(CCSR_CATEGORY_DESCRIPTION %in% other_diagnoses) %>%
  mutate(status = 1) %>%
  pivot_wider(names_from = CCSR_CATEGORY_DESCRIPTION, values_from = status)

head(other_diagnoses_data)
```

```{r}
# get data for all diabetes diagnoses
diabetes_only_data <- diabetes_full %>%
  filter(CCSR_CATEGORY_DESCRIPTION %in% diab_names) %>%
  mutate(STATE = case_when(CCSR_CATEGORY_DESCRIPTION == "Prediabetes" ~ 1,
                           CCSR_CATEGORY_DESCRIPTION == "Diabetes.mellitus.without.complication" ~ 2,
                           CCSR_CATEGORY_DESCRIPTION == "Diabetes.mellitus.with.complication" ~ 3)) %>%
  select(-CCSR_CATEGORY_DESCRIPTION) %>%
  arrange(desc(BENE_ID), TIME_SINCE_ENROLLMT) 

head(diabetes_only_data)
```



```{r}
diabetes_transformed <- full_join(
  diabetes_only_data, other_diagnoses_data, by = c("BENE_ID", "TIME_SINCE_ENROLLMT")) %>%
  group_by(BENE_ID) %>%
  summarise(new_rows = list(bind_rows(tibble(TIME_SINCE_ENROLLMT = 0), cur_data()))) %>%
  unnest(new_rows) %>%
  ungroup() %>%
  mutate(STATE = ifelse(is.na(STATE), 0, STATE)) %>%
  arrange(desc(BENE_ID), TIME_SINCE_ENROLLMT)

head(diabetes_transformed)
```


```{r}
update_state_iteratively <- function(data) {
  repeat {
    # store previous state values to check for convergence
    prev_state <- data$STATE
    
    # update STATE iteratively for second to last rows
    data <- data %>%
      group_by(BENE_ID) %>%
      mutate(STATE = ifelse(row_number() > 1 & STATE == 0, lag(STATE), STATE)) %>%
      ungroup()
    
    # break the loop if no changes were made
    if (all(prev_state == data$STATE)) break
  }
  return(data)
}

diabetes_transformed <- update_state_iteratively(diabetes_transformed)
```


```{r}
update_diagnoses_iteratively <- function(data, cols) {
  data <- data %>%
    group_by(BENE_ID) %>%
    mutate(across(all_of(cols), ~ replace(.x, row_number() == 1, 0))) %>% # Set first row to 0
    ungroup()
  
  repeat {
    prev_data <- data[cols]  # store previous state for checking convergence
    
    # perform iterative update until all NAs are filled
    data <- data %>%
      group_by(BENE_ID) %>%
      mutate(across(all_of(cols), ~ ifelse(is.na(.x), lag(.x, default = 0), .x))) %>%
      ungroup()
    
    # break loop if no changes are made
    if (identical(prev_data, data[cols])) break
  }
  
  return(data)
}

diabetes_transformed <- update_diagnoses_iteratively(diabetes_transformed, other_diagnoses)
```


```{r}
# filter out time=0
diabetes_transformed <- diabetes_transformed %>%
  filter(TIME_SINCE_ENROLLMT != 0)

# merge with data from enrollment file
enrollment_diab <- read.csv("/Users/benabijah/Downloads/enrollment_diab.csv", header = T) %>%
  mutate(BENE_ID = as.character(BENE_ID)) %>%
  select(-BENE_ENROLLMT_REF_YR)

diabetes_transformed <- left_join(
  diabetes_transformed, enrollment_diab, by = c("BENE_ID"))

head(diabetes_transformed)
```







